@startuml

class Employee {
    -String firstName
    -String lastName
    -int salary
}

class EmployeeReader {
    -LinkedList<Employee> Employee
    -BufferedReader reader;
    -BufferedWriter writer;

    +readEmployee(String fileName)
    +saveEmployee(string fileName)
    +writeEmployees(string fileName)

}

@enduml