@startuml

class WebsiteGenerator {
    -FileWriter writer;
    -String websiteName;

    +generateWebsiteDirectory()
    +generateIndex(String authorName)
    +generateWebsiteCSSDir()
    +generateWebsiteJSDir()
}

@enduml