@startuml

class Product {
    -String name;
    -double price;
    -int quantity;

    +printProduct();
}

class ProductReader {
    -List<Product> products;
    -Gson gsonReader;

    +readProducts(String fileName);
    +findProduct(String productName);
}

@enduml